### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by justin13888** [gaurishhs/elysia-ip#12]
![image](https://github.com/gaurishhs/elysia-ip/assets/20733699/a400afe2-a8c4-4a9e-b614-b23913439cd3)

Tried to using example code in README. Unable to import. Any hints as to why?

Some dependency versions:
- elysia: 1.0.9
- elysia-ip: 1.0.0

**Comment by gaurishhs** [comment]
hi, can you try this https://github.com/gaurishhs/elysia-ip/issues/11#issuecomment-2019431434 If it works i will release a fix

**Comment by justin13888** [comment]
Appreciate quick response. I tried that but the TypeScript LSP just gives me another error.
![image](https://github.com/gaurishhs/elysia-ip/assets/20733699/ed7ca3c3-553d-45ae-b246-c2c13e9f2cf2)
The error is coming from the `ip` parameter.

![image](https://github.com/gaurishhs/elysia-ip/assets/20733699/f5f4675c-e563-44e0-8486-bce82a100ba3)

**Comment by justin13888** [comment]
<https://github.com/gaurishhs/elysia-ip/issues/11#issuecomment-2019431434> is probably the fix so I'm closing

**Comment by gaurishhs** [comment]
hi, please update to v1.0.2 (latest) containing this fix.
