### ISSUE TITLE
Duplicate run when use multiple time & Add injectServer & Remove throw error it make app crash

### ISSUE THREAD

**Issue by armada45-pixel** [gaurishhs/elysia-ip#18]
Duplicate when use multiple time.
Fix by using new Elysia() and name it using Elysia({ name: "elysia-ip" })

Planing add option injectServer like
https://github.com/rayriffy/elysia-rate-limit/blob/main/example/muliInstanceInjected.ts
for fix issue like https://github.com/rayriffy/elysia-rate-limit/issues/29

Remove throw error it make app crash
https://github.com/gaurishhs/elysia-ip/blob/f46952e0baa39e63aaabe19a2ada291e8ee87036/src/index.ts#L49

Fixed in Fork
https://github.com/armada45-pixel/elysia-ip/blob/main/src/index.ts

**Comment by gaurishhs** [comment]
I don't see any changes in the fork

**Comment by armada45-pixel** [comment]
Duplicate 
https://github.com/armada45-pixel/elysia-ip/blob/7822c81fe9490b4bf1c235cd29465dfcc8151a0d/example/issue.ts#L18-L42
![image](https://github.com/gaurishhs/elysia-ip/assets/59261678/adf22959-79c5-46f1-a5ec-7fef0ab9706e)

**Comment by armada45-pixel** [comment]
Remove throw error
https://github.com/gaurishhs/elysia-ip/blob/f46952e0baa39e63aaabe19a2ada291e8ee87036/src/index.ts#L49

**Comment by armada45-pixel** [comment]
Fixed https://github.com/gaurishhs/elysia-ip/issues/14
