### ISSUE TITLE
How to retrieve ONLY IPv4 address

### ISSUE THREAD

**Issue by cholasimmons** [gaurishhs/elysia-ip#21]
Does this plugin have a function to return only the IPv4 address without the ffff prefix?

**Comment by gaurishhs** [comment]
Which runtime are you using?

**Comment by cholasimmons** [comment]
I'm on Bun 1.1.8 @gaurishhs

**Comment by gaurishhs** [comment]
You should ask this on the Bun repo then since we just use the IP Bun provides. I don't think so it is possible because Bun provides the IP client is using as default. If your client is using IPv6 it will give IPv6 same for IPv4

**Comment by cholasimmons** [comment]
Makes sense. Thanks.
