### ISSUE TITLE
Suggestion: IP Headers > server.requestIP for Bun

### ISSUE THREAD

**Issue by uhidontkno** [gaurishhs/elysia-ip#27]
Exactly what the title says, use IP headers (eg. `X-Forwarded-For`) over `server.requestIP` if the IP headers exist.

**Comment by gaurishhs** [comment]
Why is that so? You can disable requestIP by setting `headersOnly` to true in the options tho but i dont see a reason to use headers over socket address

**Comment by uhidontkno** [comment]
> Why is that so?

Makes things easier because you'd need to do something like this to not potentially break things if one would want to deploy an Elysia app that uses elysia-ip behind a reverse proxy (without changing the code)
```ts
app.use(ip({ headersOnly: Boolean(process.env.PROXIED || "false") }));
```

**Comment by gaurishhs** [comment]
I think Elysia's primary focus is still the runtime. Cf and Fastly work due to WinterCG compatibility.
