### ISSUE TITLE
Bun can't build

### ISSUE THREAD

**Issue by Torwent** [gaurishhs/elysia-ip#29]
Maybe it's me who's doing something wrong but I can't use `Bun build` command with this package installed.

Running `bun build src/index.ts --outdir build`
Gives me the following error:
```
1 | import { debuglog } from "node:util";
             ^
error: No matching export in "node:util" for import "debuglog"
    at PATH_TO_PROJECT\node_modules\elysia-ip\dist\services\debug.js:1:10
error: script "build" exited with code 1
```

**Comment by Torwent** [comment]
Also, not entirely sure if this is a Bun issue and not an issue of this project! Sorry if that's the case!

**Comment by gaurishhs** [comment]
What is your Bun version?

**Comment by Torwent** [comment]
version 1.1.13
