### ISSUE TITLE
use(ip()) causes typescript to not recognize the param types

### ISSUE THREAD

**Issue by samyung0** [gaurishhs/elysia-ip#4]
After installing the plugin and using it like `use(ip())`,
the typescript engine is complaining that in route handling `.get("/id/:id", ({ params: { id } }) => id)`, `id` has type `any`.
The same goes for other params as well: `.onError(({ code, error }) => {
    return new Response(error.toString());
  });`, `code` and `error` have type `any`
  
  My Elysia version is 0.8.8 and I am using version elysia-ip 0.0.5

**Comment by samyung0** [comment]
Sorry this is my bad. I did not notice that it was complaining `Could not find a declaration file for module 'elysia-ip'`.
The whole error looks like this:
![image](https://github.com/gaurishhs/elysia-ip/assets/41984660/2c16c870-b34a-4287-a69d-b729f3817299)

**Comment by gaurishhs** [comment]
The types error has been fixed. Please upgrade to version `0.0.6` for the fix
