### ISSUE TITLE
Error: Property 'ip' does not exist on type on 0.0.7

### ISSUE THREAD

**Issue by ReesMorris** [gaurishhs/elysia-ip#8]
Hi! I'm running into an issue while following the basic implementation guide from the docs:

```
import { Elysia } from "elysia";
import { ip } from "elysia-ip";

new Elysia().use(ip()).get("/", ({ ip }) => ip).listen(3000);
```

On version `^0.0.7`, TypeScript throws a `Property 'ip' does not exist on type` error for the `{ ip }` reference.

This error disappears when I downgrade to version `^0.0.6`, where `ip` is correctly typed as
`string | SocketAddress | null | undefined`

My environment is using the latest Bun version (`v1.0.27`), with all other dependencies up to date, including TypeScript (`^5.3.3`) and Elysia (`^0.8.17` or `latest`).

I have attached screenshots to illustrate the issue (`0.0.7` left, and `0.0.6` right), but please let me know if there are any issues accessing them or if further details are required.

<img width="303" alt="SCR-20240219-ucfy" src="https://github.com/gaurishhs/elysia-ip/assets/25528100/8d2d3cf0-e12e-4bbb-b84b-b610eddc6fb8">

<img width="345" alt="SCR-20240219-uckv" src="https://github.com/gaurishhs/elysia-ip/assets/25528100/4d2995b5-06f5-4468-b64d-1c61f2d8dc61">

**Comment by gaurishhs** [comment]
This was covered in #5 I don't really know what could cause the issue now. Previous implementation did work for some and doesn't for some. There must be some sort of incompatibility.  I'd suggest if 0.0.6 works stay on that.

**Comment by ReesMorris** [comment]
Sure, its definitely a weird one. Thanks anyway!
